-- 'mg979/vim-visual-multi'
--vim.keymap.set(
--    {"n"},
--    "<C-k>",
--    ":call vm#commands#add_cursor_up(0, v:count1)<cr>",
--    { noremap = true, silent = true }
--) 
--
--vim.keymap.set(
--    {"n"},
--    "<C-j>",
--    ":call vm#commands#add_cursor_down(0, v:count1)<cr>",
--    { noremap = true, silent = true }
--)
